let arr = ["Mihir ", "Kate"];
console.log(arr);
let nums = [2, "Mihir", 3, 4, 6, 78];
console.log(nums[4]);
let m = [];
console.log(nums[1][4]);
let fruits = ["Mango", "apple", "Kivi"];
console.log(fruits);
fruits[9] = "guawa";
fruits[5] = "baboo;";
console.log(fruits);
let cars = ["Fer", "Bosc"];
console.log(cars);
cars.push("mihir");
console.log(cars);
console.log(cars.pop());
